first try
danilpanshin/TestGuru pull request #10
Opened 2018-02-02 20:31 UTC by danilpanshin

2018-02-03 14:21 UTC, psylone requested changes

2018-02-03 14:21 UTC, psylone commented on app/models/test_passage.rb
> +    #self.current_question = next_question
Лучше удалять такие комментарии.

2018-02-03 14:21 UTC, psylone commented on app/models/test_passage.rb
> +  before_validation :before_validation_set_next_question, on: :update
По факту, оба обратных вызова отвечают за установку очередного вопроса поэтому можно использовать единственный обратный вызов.

2018-02-03 14:21 UTC, psylone commented on app/views/test_passages/result.html.erb
> +	<%= if @test_passage.success
Здесь должно быть `<%%>`, без `=`,  поскольку `if` - это управляющая конструкция. Если нужно что-то вывести, это нужно выводить внутри `if`.

2018-02-03 14:21 UTC, psylone commented on app/views/test_passages/result.html.erb
> +		  render plain: 'The test passed successfully'
`render` - лишнее, просто выводи текст. Получается такая логика, ERB читает шаблон, видит `if` и выводит либо то что в одной его ветви, либо то что в другой. То есть `ERB` вычисляет условие `if`, а дальше ведет себя внутри ветви так будто `if`-а и нет вовсе.

2018-02-03 14:21 UTC, psylone commented on app/views/test_passages/result.html.erb
> +		end %>
Хороший кейс чтобы понять различия между тем что стоит в шаблоне держать и что нет. Вот если бы у нас здесь была только логика вывода (без присваивания), то можно было бы оставить всё как есть. Но как только появляется присваивание, появляется некоторая бизнес-логика приложения которую в шаблоне лучше не держать. Используй хэлпер.

2018-02-03 14:21 UTC, psylone commented on app/models/test_passage.rb
> +  	percent > SUCCESS
В таком узком контексте что такое `percent` и `SUCCESS` в общем понятно. Но при росте приложения высока вероятность что степень понятности уменьшится. Поэтому лучше сделать имена более явными, например `percent_of_completion`.

2018-02-04 14:28 UTC, psylone approved these changes

2018-02-04 14:28 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +	  @color = 'block_red'
Лучше обходиться без инстанс переменных в хэлперах поскольку с ними код становится более зависимым. Мы уже не может исключить состояние из хэлпера (ведь оно устанавливается в инстанс переменной).

Стоит работать с хэлперами как с функциями: передал аргументы, получил ответ.

2018-02-04 14:28 UTC, psylone commented on app/views/test_passages/result.html.erb
> +	Correct answers: <span class="<%= @color %>"><%= @test_passage.percent_of_complition %>%</span>
Совсем не очевидно что `@color` устанавливается в `number_color`. Лучше сделать два хэлпера.

2018-02-05 18:06 UTC, danilpanshin commented on app/helpers/test_passages_helper.rb
> +	  @color = 'block_red'
Поправил. Сделал два хелпера, убрал переменную https://github.com/danilpanshin/TestGuru/pull/10/commits/09dcb662c8135367bc7cb7e40a0686d7b5fee4d8

2018-02-05 21:07 UTC, merged