timer first ver
danilpanshin/TestGuru pull request #20
Opened 2018-03-14 17:07 UTC by danilpanshin

2018-03-14 17:09 UTC, danilpanshin commented on app/controllers/test_passages_controller.rb
> +    @time = Time.now + 7
тут естественно вместо + 7 будет + @test_passage.test.timer.minutes

2018-03-14 22:44 UTC, psylone requested changes

2018-03-14 22:44 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +  TIME = Time.now
Эм, что это? Время в константе будет иметь значение времени на момент определения константы, то есть на момент загрузки приложения, а **не** в момент выполнения запроса.

2018-03-14 22:44 UTC, psylone commented on app/views/test_passages/show.html.erb
> +</script>
Это нужно вынести в ассеты, в отдельный JavaScript-файл.

2018-03-14 22:44 UTC, psylone commented on app/views/test_passages/show.html.erb
> +<script language="JavaScript" src="https://scripts.hashemian.com/js/countdown.js"></script>
Используй Asset Pipeline для подключения скриптов.

2018-03-14 22:44 UTC, psylone commented on app/views/test_passages/show.html.erb
> +</script>
API таймера конечно желает лучшего.

2018-03-19 22:06 UTC, psylone approved these changes

2018-03-19 22:06 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +      TestsMailer.completed_test(@test_passage).deliver_now
Наверное письмо не стоит отправлять, тест-то не выполнен по факту если время вышло.

2018-03-19 22:06 UTC, psylone commented on app/models/test_passage.rb
> +      (Time.now - self.created_at) > self.test.timer
`test.timer && (Time.now - created_at) > test.timer`.

2018-03-20 21:40 UTC, merged