Rails badges
danilpanshin/TestGuru pull request #21
Opened 2018-03-26 19:49 UTC by danilpanshin

2018-03-27 00:07 UTC, psylone requested changes

2018-03-27 00:07 UTC, psylone commented on app/controllers/admin/badges_controller.rb
> +    @badges = Test.all
Что это? Почему бэйджам присваиваются тесты?

2018-03-27 00:07 UTC, psylone commented on app/services/reward.rb
> +      @user.badges << Badge.where("title = 'first blood'")
Могут быть и другие бэйджи с почти таким же правилом.

2018-03-27 00:07 UTC, psylone commented on app/services/reward.rb
> +  def check_rule
Это не совсем `check_rule`, ведь самая главная задача - выдача бэйджей.

2018-03-27 00:07 UTC, psylone commented on app/services/reward.rb
> +    if @user.test_passages.last.success_test? && @user.tests.where("title = ?", @user.tests.last.title).count == 1
Условие лучше вынести в отдельный приватный метод.

2018-03-27 00:07 UTC, psylone commented on app/services/reward.rb
> +    if @user.test_passages.last.success_test? && @user.tests.where("title = ?", @user.tests.last.title).count == 1
Лучше отталкиваться от текущего объекта `@test_passage`, чем от `last`.

2018-03-27 00:09 UTC, danilpanshin commented on app/controllers/admin/badges_controller.rb
> +    @badges = Test.all
глаз замылился...

2018-03-27 15:26 UTC, danilpanshin commented on app/services/badges_reward.rb
> +    if test_passed_on_the_first_try? && backender? && first_level_all_tests?
Логика получилась совсем неуклюжая, но ничего другого в голову пока не идет. Понятно, что с добавлением еще пары бейджей она очень сильно разрастётся

2018-03-28 07:14 UTC, psylone requested changes

2018-03-28 07:14 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +      if badge.badge_success?
Лучше просто `badge.success?` или `badge.rewarded?`.

2018-03-28 07:14 UTC, psylone commented on app/services/badges_reward.rb
> +    if test_passed_on_the_first_try? && backender? && first_level_all_tests?
Давай с тобой доработаем этот момент, это важно. Вместо того чтобы определять правила в переменные `@badge_first_try` и остальные, нам нужно наоборот, абстрагироваться от этого.

Идея в том чтобы мы не знали о том сколько и какие правила существуют в бэйджах. Но знали о том как каждое правило обрабатывать и проверять. Поэтому логика должна быть примерно такой:

```ruby
def call
  Badge.all.each do |badge|
    reward_user!(badge) if send("passed_#{badge.rule_name}_rule?", badge.rule_value)
  end
end


private

def passed_first_time_rule?
end
```

Здесь мы отделяем логику проверки для каждого правила от обхода бэйджей. Мы также можем назначить, например два бэйджа за успешное прохождение всех тестов уровня `0` и уровня `1`. По сути это одинаковые абсолютно правила, у них только уровень различается. Поэтому в `rule_name` у нас будет что-то вроде `all_tests_with_level`, а в `rule_value` будет `0` и `1`. И это будет 2 записи в `badges`. Когда мы будем итерировать по ним, мы проверим 2 раза одно и то же правило.

2018-03-29 02:24 UTC, psylone approved these changes

2018-03-29 14:18 UTC, merged