Scopes validations
danilpanshin/TestGuru pull request #7
Opened 2018-01-19 15:13 UTC by danilpanshin

2018-01-20 02:07 UTC, psylone requested changes

2018-01-20 02:07 UTC, psylone commented on app/models/question.rb
> +  scope :right, -> {where(correct: true)}
Проверь как это работает.

2018-01-20 02:07 UTC, psylone commented on app/models/test.rb
> +  scope :by_category, -> (category) { joins(:category).where('categories.title = ?', category).order(title: :desc)}
Можно так: `joins(:category).where(categories: { title: category })`.

2018-01-20 02:07 UTC, psylone commented on app/models/test.rb
> +  scope :by_category, -> (category) { joins(:category).where('categories.title = ?', category).order(title: :desc)}
Не стоит здесь же вызывать метод `order`, лучше так: `Test.by_category(:art).order(title: :desc)`.

2018-01-20 02:07 UTC, psylone commented on app/models/test.rb
>    #end
Нужно было выбирать только названия так что метод должен остаться.

2018-01-20 02:07 UTC, psylone commented on app/models/test.rb
> +                    uniqueness: { scope: :level,
Нужен составной уникальный индекс.

2018-01-20 02:07 UTC, psylone commented on app/models/test.rb
> +  scope :beginner, -> { where(level: 0..1) }
Можно так: `scope :beginner, -> { by_level(0..1) }`.

2018-01-20 02:07 UTC, psylone commented on app/models/question.rb
> +    errors.add(:answers, 'wrong number of answers') if questions.answers.size > 4 && questions.answers.size < 1
Это условие никогда не будет верным.

2018-01-20 02:07 UTC, psylone commented on app/models/question.rb
> +    errors.add(:answers, 'wrong number of answers') if questions.answers.size > 4 && questions.answers.size < 1
Подумай также нужно ли что-то проверять на стороне модели ответа, поскольку мы можем создавать отдельно ответы для какого-то определённого вопроса.

2018-01-20 11:43 UTC, danilpanshin commented on app/models/test.rb
> +                    uniqueness: { scope: :level,
добавил индекс в schema, но так и не понял этот момент, а тупо скопипастил

2018-01-20 18:06 UTC, psylone commented on app/models/test.rb
> +                    uniqueness: { scope: :level,
Посмотри плиз ещё раз скринкаст о валидациях (Материал 2) с 10-й минуты.

2018-01-20 18:11 UTC, psylone requested changes

2018-01-20 18:11 UTC, psylone commented on app/models/test.rb
> +        .pluck('tests.title')
У нас же есть скоуп `by_category`, используй его в методе.

2018-01-20 18:11 UTC, psylone commented on app/models/test.rb
> +  Test.by_category('Backend').order(title: :desc).pluck(:title)
Зачем здесь нужно это выражение?

2018-01-20 18:11 UTC, psylone commented on app/models/answer.rb
> +    errors.add(:question, 'wrong number of answers') if !(1..4).include?(question.answers.count)
Можно использовать `unless` вместо `if` и отрицания.

2018-01-21 13:29 UTC, psylone approved these changes

2018-01-21 13:29 UTC, psylone commented on app/models/test.rb
> +    Test.by_category(category).order(title: :desc).pluck(:title)
👍

2018-01-22 08:43 UTC, merged